### ISSUE TITLE
errro uploading CohortDiagnostics in ShinyApp

### ISSUE THREAD

**Issue by golozara** [ohdsi-studies/PioneerWatchfulWaiting#14]
I am getting the following when I am trying to upload the NCR, Bordeaux and MDH data to ShinyApp. This will then results in empty shells in the ShinyApp
 
 > CohortDiagnostics::preMergeDiagnosticsFiles(file.path(outputFolder, "NCR"))
.
.
.
Processing table concept_synonym
Warning: Table concept_synonym in zip file /Users/asieh.golozar/Desktop/CD/Strata/NCR/Results_NCR.zip has duplicate rows. Removing 19 records.

Processing table incidence_rate
Warning: Table incidence_rate in zip file /Users/asieh.golozar/Desktop/CD/Strata/NCR/Results_NCR.zip has duplicate rows. Removing 9108 records.
 
> CohortDiagnostics::launchDiagnosticsExplorer(file.path(outputFolder, "NCR"))

Listening on http://127.0.0.1:4453 
Warning: warning: Values are not uniquely identified; output will contain list-cols.
* Use `values_fn = list` to suppress this warning.
* Use `values_fn = length` to identify where the duplicates arise
* Use `values_fn = {summary_fun}` to summarise duplicates

Warning: Error in FUN: invalid argument to unary operator
  110: eval
  109: eval
  108: Ops.data.frame
  104: exprFunc [/Users/asieh.golozar/Library/R/3.6/library/CohortDiagnostics/shiny/DiagnosticsExplorer/server.R#353]

**Comment by keesvanbochove** [comment]
This is likely caused by the fact that all three of these result sets have different cohorts than the Shiny app expects. Bordeaux and MDH were run with an older version of the package, and the NCR cohort definitions are suffering from a character set - related problem. In order to be able to fix and debug this easier in the future, we are adding metadata to the cohort diagnostics results (see https://github.com/ohdsi-studies/PioneerWatchfulWaiting/pull/15).

**Comment by keesvanbochove** [comment]
@Anne0507 could you check if an error like this still appears with the latest results files from running v0.3.2?
