### ISSUE TITLE
Error in runStudy step

### ISSUE THREAD

**Issue by rfherrerac** [ohdsi-studies/PioneerWatchfulWaiting#20]
after runStep, I got this error :  Error: Error executing SQL:
java.sql.SQLException: [Amazon](500310) Invalid operation: syntax error at or near ")" 
Position: 593; attached the error report. 

[errorReportSql.txt](https://github.com/ohdsi-studies/PioneerWatchfulWaiting/files/6271634/errorReportSql.txt)

**Comment by YorgosA** [comment]
Hi Ronald,

The query is expecting a number of cohort ids but there is none. 
Check line #20 in the errorReportSql.txt ( _o.cohort_definition_id IN ()_ )

**Comment by keesvanbochove** [comment]
Right exactly @YorgosA. Just stepping through, this is caused by this line: https://github.com/ohdsi-studies/PioneerWatchfulWaiting/blob/862b0dbc03c85aebee3ce023f929943fa6dd19c0/R/RunStudy.R#L189
Which if you isolate and run it, creates an empty list.
```>   combinedOutcomeIds <- allStudyCohorts[allStudyCohorts$name %in% c('Death',$
> combinedOutcomeIds
numeric(0)```

Which is caused in turn by [getAllStudyCohorts](https://github.com/ohdsi-studies/PioneerWatchfulWaiting/blob/862b0dbc03c85aebee3ce023f929943fa6dd19c0/R/ResourceFiles.R#L62) returning a table that contains ids for names.
```

**Comment by keesvanbochove** [comment]
We can fix this by restoring the names in the 'name' columns in `inst/settings/CohortsToCreate...csv`, but it does beg the question which of the outcomes cohorts should be included in the combined survival analysis. Still only Death and Symptomatic progression? (see https://github.com/ohdsi-studies/PioneerWatchfulWaiting/blob/master/inst/settings/CohortsToCreateOutcome.csv) @MaximMoinat would it be possible to re-insert names in the names column, or was there another reason why the autogenerated cohort files now contain identifiers there?

**Comment by MaximMoinat** [comment]
The name column is used to create the filenames for the cohorts (`.json`, `.sql`) by `ROhdsiWebApi::insertCohortDefinitionSetInPackage()`. I did not want to change the filenames, so I added the ids in there as well.

**Comment by MaximMoinat** [comment]
@keesvanbochove Simple fix made by simply referencing to the cohorts using the id
