### ISSUE TITLE
Shiny app v0.4.4 - cohort characterization & cohort comparison empty

### ISSUE THREAD

**Issue by bdemeulder** [ohdsi-studies/PioneerWatchfulWaiting#89]
The tables in cohort char and compare cohort char are empty in the newest version of the package, using the PreMerge data available in teams.

![Shiny app 04102021](https://user-images.githubusercontent.com/11734167/135839035-e6122629-5971-4df2-96f6-1bca0d6768bf.png)

The error says "the replacement table has 1 line, the replaced table as 0".

Attaching traceback as well.
![Shiny app 04102021- traceback](https://user-images.githubusercontent.com/11734167/135839348-cc8b2004-a834-436a-baa3-d08b7159dafe.png)
ll

**Comment by keesvanbochove** [comment]
Looks like this is caused by https://github.com/ohdsi-studies/PioneerWatchfulWaiting/commit/d865b1984a790da3b3498f500c5a5362c1578be0, fread sees the covariateId column as double while read.csv interpreted as string. As a result global.r:139 no longer works.
Possible fix:
`covIdsAsString <- as.character(covariate$covariateId)
  covariate$windowId <- as.numeric(substr(covIdsAsString, nchar(covIdsAsString), nchar(covIdsAsString)))`
